# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /elb

# Copy the current directory contents into the container at /app
COPY . /elb

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org Flask boto3

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run app.py when the container launches
CMD ["python", "elb.py"]
